/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      lineHeight: {
        11: "3rem",
        12: "4rem",
        13: "5rem",
        14: "6rem",
        15: "7rem",
      },
      letterSpacing: {
        tightest: "-.075em",
      },
      spacing: {
        128: "32rem",
        144: "36rem",
        160: "44rem",
      },
      fontFamily: {
        poleno: ["poleno", "sans-serif"],
        "forma-djr": ["forma-djr-micro", "sans-serif"],
        merriweather: ["merriweather", "serif"],
        athelas: ["Athelas"],
        zemke: ["zemke"],
        sunbeat: ["sunbeat"],
        kidprint: ["kidprint"],
        "kidprint-bold": ["kidprint-bold"],
        misterk: ["misterk"],
        children: ["children"],
        doingwise: ["doingwise"],
        drawingkids: ["drawingkids"],
        kidshand: ["kidshand"],
        missinglovely: ["missinglovely"],
        neubau: ["neubau"],
        singeldust: ["singeldust"],
        sweetcinnamon: ["sweetcinnamon"],
        verveine: ["verveine"],
        winterpen: ["winterpen"],
        zai1870: ["zai1870"],
        zaisloppy: ["zaisloppy"],
        zaithin: ["zaithin"],
        zaihandwritten: ["zaihandwritten"],
        zaigraffiti: ["zaigraffiti"],
      },
    },
  },
  plugins: [],
};
